[package]
name = "encoder"
version = "0.1.0"
edition = "2024"

[dependencies]
z3 = "0.13"
ir = { path = "../ir" }
parser = { path = "../parser" }
enchelper = { path = "../enchelper" }
hltlunroller = { path = "../hltlunroller" }
ahltlunroller = { path = "../ahltlunroller" }